# NumPy

## What is NumPy ?

 * It's a python library used for working with arrays.
 * Has functions for working in domain of linear algebra, fourier transform, and matrices.
 * Stands for Numerical Python
 
## Why Use NumPy ?
 
 * In python we have list which works as array but that is slow to process
 * NumPy aims to provide array which is 50X times faster than traditional python list.
 
 
## Why NumPy is faster than Python List ?

 1. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science.


### To import NumPy:
    
   **import numpy as np**
    
### NumPy Array

    NumPy is used to work with arrays. The array object in NumPy is called ndarray.
    We can create a NumPy ndarray object by using the array() function

## Data types in NumPy


Below is a list of all data types in NumPy and the characters used to represent them.

* **i** - integer
* **b** - boolean
* **u** - unsigned integer
* **f** - float
* **c** - complex float
* **m** - timedelta
* **M** - datetime
* **O** - object
* **S** - string
* **U** - unicode string
* **V** - fixed chunk of memory for other type ( void )

To check the data type of NumPy use dtype.

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Dimensions in Array


* 1-D (shape(x,)) x= row (axis 0)
* 2-D (shape(x,y)) x = row (axis 0), y = column (axis 1)
* 3-D (shape (x,y,z)) x = axis 0, y = axis 1, z = axis 3

The number of dimension is the rank of the array.

In [8]:
d_1_arr = np.array([1,2,3])
print(d_1_arr)
print(f'Rank of the d_1_arr is {d_1_arr.ndim}')

print('---------------')

d_2_arr = np.array([[1,2,3],[4,5,6]])
print(d_2_arr)
print(f'Rank of the d_2_arr is {d_2_arr.ndim}')

print('----------------')

d_3_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d_3_arr)
print(f'Rank of the d_3_arr is {d_3_arr.ndim}')

[1 2 3]
Rank of the d_1_arr is 1
---------------
[[1 2 3]
 [4 5 6]]
Rank of the d_2_arr is 2
----------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Rank of the d_3_arr is 3


In [9]:
higher_dimensional_arr = np.array([1,2,3,4,5], ndmin=5)
print(higher_dimensional_arr)
print(f'Rank of higher_dimensional_arr is {higher_dimensional_arr.ndim}')

[[[[[1 2 3 4 5]]]]]
Rank of higher_dimensional_arr is 5


## Array Indexing

Array indexing is the same as accessing an array element.You can access an array element by referring to its index number.

### Access 1-D Array Elements

In [10]:
print(f'1-D array : {d_1_arr}')
print(f'2nd Element of the d_1_arr is : {d_1_arr[1]}')

1-D array : [1 2 3]
2nd Element of the d_1_arr is 2


### Access 2-D Arrays:

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element. 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [14]:
print(f'2-D array : {d_2_arr}')
print(f'2nd Element of the 1st row is : {d_2_arr[0,1]}')

2-D array : [[1 2 3]
 [4 5 6]]
2nd Element of the 1st row is : 2


### Access 3-D Arrays:

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


## Explanation of Accessing the element of 3-D Array

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

## Negative Indexing

Use negative indexing to access an array from the end.

In [21]:
print(f'2-D array : {d_2_arr}')
print(f'Last element of the array is : {d_2_arr[1,-1]}')

2-D array : [[1 2 3]
 [4 5 6]]
Last element of the array is : 6


## NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: **[start:end]**

We can also define the step, like this: **[start:end:step]**

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [23]:
d_1_array = np.array([0,1,2,3,4,5,6,7,8,9])
print(f'Original Array is : {d_1_array}')
print(f'Sliced Array : {d_1_array[1:8:2]}')

Original Array is : [0 1 2 3 4 5 6 7 8 9]
Sliced Array : [1 3 5 7]


## Slicing through a 2-D Array

In [25]:
d_2_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(f'Original Array is : {d_2_array}')
print(f'Sliced Array : {d_2_array[1,1:4]}')

Original Array is : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Sliced Array : [7 8 9]


In [27]:
# From both array return the 2nd element
print(d_2_array[0:,2])

[3 8]


In [28]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
print(d_2_array[0:,1:4])

[[2 3 4]
 [7 8 9]]


## Negative Slicing

minus operator to refer to an index from the end

In [29]:
#Slice from the index 3 from the end to index 1 from the end
print(d_1_array[-3:-1])

[7 8]


### Boolean Slicing
we can use Boolean slicing to select elements of a numpy array.

In [22]:
arr = np.array([1,2,3,4,5,6,7,8])
print(f'arr[arr > 2] = {arr[arr > 2]}')

arr[arr > 2] = [3 4 5 6 7 8]


## NumPy Array Copy vs View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [30]:
array_one = np.array([1,2,3,4,5,6])
array_two = np.array([11,12,13,14,15,16])

arr_copy = array_one.copy()
arr_view = array_two.view()

print('Before : \n')
print('Original Array C: ',array_one)
print('Original Array V: ',array_two)
print('Copied Array : ',arr_copy)
print('Viewed Array : ',arr_view)


arr_copy[2] = 44
arr_view[5] = 0

print('After : \n')
print('Original Array : ',array_one)
print('Original Array V: ',array_two)
print('Copied Array : ',arr_copy)
print('Viewed Array : ',arr_view)

Before : 

Original Array C:  [1 2 3 4 5 6]
Original Array V:  [11 12 13 14 15 16]
Copied Array :  [1 2 3 4 5 6]
Viewed Array :  [11 12 13 14 15 16]
After : 

Original Array :  [1 2 3 4 5 6]
Original Array V:  [11 12 13 14 15  0]
Copied Array :  [ 1  2 44  4  5  6]
Viewed Array :  [11 12 13 14 15  0]


## Shape of the Array

The shape of an array is the number of elements in each dimension. NumPy arrays have an attribute called *shape* that returns a tuple with each index having the number of corresponding elemen

In [35]:
np_array_one = np.array([1,2,3])
np_array_two = np.array([[1,2,3,4],[5,6,7,8]])
np_array_three = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(f'Shape of the 1-D array is : {np_array_one.shape}')
print(f'Shape of the 2-D array is : {np_array_two.shape}')
print(f'Shape of the 3-D array is : {np_array_three.shape}')

Shape of the 1-D array is : (3,)
Shape of the 2-D array is : (2, 4)
Shape of the 3-D array is : (2, 2, 3)


### Shape Description:

#### 1-D Array:
1-D arrays can be described simply by the number of values they contain. The shape of the array above would be simply described as 3. This array can also be though of as having one row and 3 columns.

#### 2-D Array:
NumPy describes 2-D arrays by first listing the number of rows then the number columns. 
**The rows of 2-D array must all contain the same number of columns.**


#### 3-D Array:
The dimensions of a 3-D array are described by the number of layers the array contains, and the number of rows and columns in each layer. NumPy reports the shape of 3-D arrays in the order layers, rows, columns.
**All layers must have the same number of rows and columns.**

## NumPy Array Reshape

Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [5]:
# Converting 1-D Array to 2-D Array

array = np.array([1,2,3,4,5,6,7,8])
new_arr = array.reshape(2,4)
print(f'Original array before reshaping : {array} \n\nArray After Reshape : {new_arr}')

Original array before reshaping : [1 2 3 4 5 6 7 8] 

Array After Reshape : [[1 2 3 4]
 [5 6 7 8]]


In [8]:
# Convert 1-D Array to 3-D Array
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(2,2,2)
print(f'Original array before reshaping : {arr} \n\nArray After Reshape : {new_arr}')

Original array before reshaping : [1 2 3 4 5 6 7 8] 

Array After Reshape : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method. Pass -1 as the value, and NumPy will calculate this number for you.

**We Cannot Pass -1 for more than 1 Dimension**

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### NumPy Array Iteration

In [18]:
# Iterating through 1-D Array
arr_one = np.array([1,2,3,4,5,6])
print(f'Original Array : {arr_one}\nIterating through 1-D array : ')
for x in arr_one:
    print(x)

#Iterating through Rows
arr_two = np.array([[1,2,3,4],[5,6,7,8]])
print(f'\nOriginal Array : {arr_two}\nIterating through 2-D array Row Wise: ')
for x in arr_two:
    print(x)
    
#Iterating by each element
print(f'\nOriginal Array : {arr_two}\nIterating through 2-D array Element Wise: ')
for x in arr_two:
    for y in x:
        print(y)
        
#Iterating through Rows
arr_three = np.array([[[1,2,3,4],[5,6,7,8]],[[11,12,13,14],[15,16,17,18]]])
print(f'\nOriginal Array : {arr_three}\nIterating through 3-D array Row Wise: ')
for x in arr_three:
    print(x)
    
#Iterating by each element
print(f'\nOriginal Array : {arr_three}\nIterating through 3-D array Element Wise: ')
for x in arr_three:
    for y in x:
        for z in y:
            print(z)

Original Array : [1 2 3 4 5 6]
Iterating through 1-D array : 
1
2
3
4
5
6

Original Array : [[1 2 3 4]
 [5 6 7 8]]
Iterating through 2-D array Row Wise: 
[1 2 3 4]
[5 6 7 8]

Original Array : [[1 2 3 4]
 [5 6 7 8]]
Iterating through 2-D array Element Wise: 
1
2
3
4
5
6
7
8

Original Array : [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
Iterating through 3-D array Row Wise: 
[[1 2 3 4]
 [5 6 7 8]]
[[11 12 13 14]
 [15 16 17 18]]

Original Array : [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
Iterating through 3-D array Element Wise: 
1
2
3
4
5
6
7
8
11
12
13
14
15
16
17
18


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration.

### Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [19]:
arr_three = np.array([[[1,2,3,4],[5,6,7,8]],[[11,12,13,14],[15,16,17,18]]])
print(f'\nOriginal Array : {arr_three}\nIterating through 3-D array Element Wise: ')
for x in np.nditer(arr_three):
  print(x)


Original Array : [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
Iterating through 3-D array Element Wise: 
1
2
3
4
5
6
7
8
11
12
13
14
15
16
17
18


### Iterating With Different Step Size
We can use filtering and followed by iteration.

In [21]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::3]):
  print(x)

1
4
5
8


### NumPy Array Creation Function

#### arange
This function creates an array within a range with regularly incrementing values.

In [25]:
a = np.arange(10) #if one argument is passed it will be considered as the stop value
print(f'a = {a}')
b = np.arange(2, 10, dtype=float) #with two arguments, the first is the start value and the second is the stop value which is excluded
print(f'b = {b}')
c = np.arange(2, 3, 0.1) #if a third parameter is passed, the value will be used as the increment
print(f'c = {c}')

a = [0 1 2 3 4 5 6 7 8 9]
b = [2. 3. 4. 5. 6. 7. 8. 9.]
c = [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


#### linspace
This function will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.

In [26]:
d = np.linspace(0, 9, 10) #the third is the number of elements to be created, including stop position
print(f'd = {d}')
e = np.linspace(1., 4., 7) 
print(f'e = {e}')

d = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
e = [1.  1.5 2.  2.5 3.  3.5 4. ]


The following creation functions define arrays based on the desired shape. These functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.

#### zeros
Creates an array with the desired shape with all elements equal to 0.

#### ones
Creates an array with the desired shape with all elements equal to 1.

#### full
Creates an array with the desired shape with all elements equal to a specified value.

#### random
Creates an array with the desired shape with all elements with random numbers.

In [28]:
a = np.zeros((2, 2))   
print(f'a = {a}')
                      
b = np.ones((5, ))    
print(f'b = {b}')     

c = np.full((3, 2), 7)  
print(f'c = {c}')              
                       
d = np.random.random((2, 3))  
print(f'd = {d}')

a = [[0. 0.]
 [0. 0.]]
b = [1. 1. 1. 1. 1.]
c = [[7 7]
 [7 7]
 [7 7]]
d = [[0.17094029 0.96808926 0.70593005]
 [0.1014458  0.42823093 0.90327854]]


### Broadcasting
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

**NumPy operations are usually done on pairs of arrays on an element-by-element basis.** In the simplest case, the two arrays must have exactly the same shape, as in the following example.

In [2]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([5.0, 7.0, 10.0])

print(f'1. The result of a + b is {a + b}')
print(f'2. The result of b - a is {b - a}')
print(f'3. The result of a * b is {a * b}')
print(f'4. The result of b / a is {b / a}')

1. The result of a + b is [ 6.  9. 13.]
2. The result of b - a is [4. 5. 7.]
3. The result of a * b is [ 5. 14. 30.]
4. The result of b / a is [5.         3.5        3.33333333]


**the smaller array is “broadcast” across the larger array so that they have compatible shapes**

### Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element wise.

    1. It starts with the trailing (i.e.rightmost) dimensions and works its way left.
    2. Two dimensions are compatible when:
        2.1. they are equal, or
        2.2. one of them is 1
    3. If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown

The **size of the resulting array is the size that is not 1 along each axis** of the inputs.

In [3]:
a = np.array([[ 0.0,  0.0,  0.0],
           [10.0, 10.0, 10.0],
           [20.0, 20.0, 20.0],
           [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
print(f'a + b = {a + b}')
print(f'shape A = {a.shape} \nshape B = {b.shape}')
b = np.array([1.0, 2.0, 3.0, 4.])
print(f'shape A = {a.shape} \nshape B = {b.shape}')
print(f'a + b = {a + b}')

a + b = [[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
shape A = (4, 3) 
shape B = (3,)
shape A = (4, 3) 
shape B = (4,)


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

### NumPy Joining Array

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [29]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [30]:
# Joining two 2-D array along with axis 1

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [31]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Stacking along rows

In NumPy, we can use helper function **hstack()** to stack along rows.

In [4]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking along columns

In NumPy, we can use helper function **vstack()** to stack along columns.

In [5]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


**The effects of hstack and vstack can be achieved with the concatenate function, using axis=1 and axis=0, respectively.**

### Stacking Along Depth (Height)

In NumPy, we can use helper function **dstack()** to stack along height, which is the same as depth.

In [6]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### NumPy Spliting Array

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use **array_split()** for splitting arrays, we pass it the array we want to split and the number of splits.



In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
#The return value is an array containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
# If the array has less elements than required, it will adjust from the end accordingly.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


We also have the method **split()** available but it will not adjust the elements when elements are less in source array for splitting like in example above, **array_split()** worked properly but **split()** would fail.

In [10]:
# Splitting 2-D Array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [11]:
# Splittng 2-D Array Axis Wise
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [12]:
# we can achieve the same thing using hsplit() function
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### NumPy Array Searching

search an array for a certain value, and return the indexes that get a match using **where()** method.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


### Search Sorted 

**searchsorted()** which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

**The searchsorted() method is assumed to be used on sorted arrays.**

In [15]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


### Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [16]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


### Multiple Values
To search for more than one value, use an array with the specified values.

In [17]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

### NumPy Sorting Arrays

Sorting means putting elements in an ordered sequence.  The most common orders are in numerical or lexicographical orders and in Numpy.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

**This method returns a copy of the array, leaving the original array unchanged.**

In [18]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [19]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [20]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [21]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [32]:
a = np.array([[7, 1, 4],[8, 6, 5],[1, 2, 3]])
print(f'1. a = {a}\n')
b = np.sort(a) # selects the last and innermost dimension, which is the rows in this example
print(f'2. b = {b}\n')
c = np.sort(a, axis=None) #None flattens the array and performs a global sort
print(f'3. c = {c}\n')

d = np.sort(a, axis=0) # you can specify which axis you want to sort - axis 0 is row
print(f'4. d = {d}\n')
e = np.sort(a, axis=1) # you can specify which axis you want to sort - axis 1 is column
print(f'5. e = {e}\n')

# Sort array indices with argsort
f = np.argsort(a)
print(f'6. Sorted indices of a = {f}')

1. a = [[7 1 4]
 [8 6 5]
 [1 2 3]]

2. b = [[1 4 7]
 [5 6 8]
 [1 2 3]]

3. c = [1 1 2 3 4 5 6 7 8]

4. d = [[1 1 3]
 [7 2 4]
 [8 6 5]]

5. e = [[1 4 7]
 [5 6 8]
 [1 2 3]]

6. Sorted indices of a = [[1 2 0]
 [2 1 0]
 [0 1 2]]


### NumPy Array Filter / Mask

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

**A boolean index list is a list of booleans corresponding to indexes in the array.**


Index-based selection solves several problems; however, there are situations you may want to filter your data based on more complicated criteria.
The concept of a **mask** in Numpy will help you addressing those fancier selections. A mask is an array with the same shape as your data, but instead of holding your values, it will hold boolean values. After creating a mask, you can use it to perform selections into your data. Using a mask will return all of the elements where the Boolean array has a True value.

In [33]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [34]:
#Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [35]:
#Creating filter Directly from Array

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


### Transpose

Other manipulations, while not quite as common as indexing or filtering, can also be very handy depending on the situation you’re in.

When you calculate the transpose of an array, every element's row and column indices are swapped. Item [0, 3], for example, becomes item [3, 0].

We can use **arr.T or arr.transpose()** to transpose any array

In [40]:
a = np.array([[1, 2],[3, 4],[5, 6]])
print(f'1. a = {a}\n')
print(f'Shape of the real array : {a.shape}\n')
print(f'2. a.T = {a.T}\n') 
print(f'Shape of the transposed array : {a.T.shape}\n')
print(f'3. a.Transpose = {a.transpose()}\n')

1. a = [[1 2]
 [3 4]
 [5 6]]

Shape of the real array : (3, 2)

2. a.T = [[1 3 5]
 [2 4 6]]

Shape of the transposed array : (2, 3)

3. a.Transpose = [[1 3 5]
 [2 4 6]]



### Concatenation
NumPy's concatenate function can be used to concatenate two arrays either row-wise or column-wise. Concatenate function can take two or more arrays of the same shape and by default it concatenates row-wise i.e. axis=0.

In [41]:
a = np.array([[4, 8],[6, 1]])
print(f'1. First array a = \n {a}\n')
b = np.array([[3, 5],[7, 2]])
print(f'2. Second array b = \n {b}\n')
c = np.concatenate((a, b)) #default axis=0
print(f'3. concatenate(a, b) = \n{c}\n')
d = np.concatenate((a, b), axis=None)
print(f'4. concatenate((a, b), axis=None) = {d}\n')
e = np.concatenate((a, b), axis=1)
print(f'5. concatenate((a, b), axis=1) = \n {e}\n')

1. First array a = 
 [[4 8]
 [6 1]]

2. Second array b = 
 [[3 5]
 [7 2]]

3. concatenate(a, b) = 
[[4 8]
 [6 1]
 [3 5]
 [7 2]]

4. concatenate((a, b), axis=None) = [4 8 6 1 3 5 7 2]

5. concatenate((a, b), axis=1) = 
 [[4 8 3 5]
 [6 1 7 2]]



### Appending
Now let's see how to append values at the end of a NumPy array. Adding values at the end of the array is sometimes necessary, mainly when the data is not fixed and is prone to change. We can use the append function to achieve that. This function can help us append single and multiple values at the end of the array.

In [42]:
a = np.array([1, 2, 3]) #1D array
print(f'1. a = {a}')
 
b = np.append(a, [4])
print(f'2. append(a, [4]) = {b}')

c = np.array([4, 5, 6])
print(f'3. c = {c}')

d = np.append(a, c)
print(f'4. append(a, c) = {d}')

1. a = [1 2 3]
2. append(a, [4]) = [1 2 3 4]
3. c = [4 5 6]
4. append(a, c) = [1 2 3 4 5 6]


Appending values at the end of the n-dimensional array can be also done through the axis. It is important that the dimensions of both the array matches otherwise it will give an error.

In [43]:
a = np.arange(1, 13).reshape(2, 6)
print(f'a = \n {a}')
  
b = np.arange(13, 19).reshape(1, 6)
print(f'b = \n {b}')

print(f'np.append(a, b, axis = 0) \n {np.append(a, b, axis = 0)}')
  
c = np.array([7, 14]).reshape(2, 1)
print(f'c = {c}')

print(f'np.append(a, c, axis = 1) \n {np.append(a, c, axis = 1)}')

a = 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
b = 
 [[13 14 15 16 17 18]]
np.append(a, b, axis = 0) 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
c = [[ 7]
 [14]]
np.append(a, c, axis = 1) 
 [[ 1  2  3  4  5  6  7]
 [ 7  8  9 10 11 12 14]]


### Union
To find union of two 1-dimensional arrays we can use function union1d() of Numpy. It returns a unique and sorted array with values that are in either of the two input arrays. If array passed as arguments to function union1d is n-dimensional, then they are flattened to 1-dimension and the outcome is computed returning sorted array with values that are in either of the two input arrays

In [44]:
a = np.array([10, 20, 30, 40])
print(f'a = {a}')  
b = np.array([20, 40, 60, 80])
print(f'b = {b}')
print(f'union(a, b) = {np.union1d(a, b)}')

c = np.array([[1, 2, 3], [4, 5, 6]])
print(f'c = \n {c}')
d = np.array([0, 5, 7])
print(f'd = {d}')
print(f'union(c, d) = {np.union1d(c, d)}')

e = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 11, 12]])
print(f'e = \n {e}')
print(f'union(c, e) = {np.union1d(c, e)}')

a = [10 20 30 40]
b = [20 40 60 80]
union(a, b) = [10 20 30 40 60 80]
c = 
 [[1 2 3]
 [4 5 6]]
d = [0 5 7]
union(c, d) = [0 1 2 3 4 5 6 7]
e = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
union(c, e) = [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Aggregating
Numpy provides many aggregate functions or statistical functions to work with a single-dimensional or multi-dimensional arrays. The numpy aggregate functions include: sum, min, max, mean, average, product, median, standard deviation, variance, argmin, argmax, percentile, cumprod, cumsum, and corrcoef. Below are some examples of their use.

In [45]:
a = np.array([[10, 30, 50], [40, 20, 90]])
print(f'1. a = \n {a}')

print(f'2. a.min() = {a.min()}') #gets the min. with no axis, array is flatten before processing
print(f'3. a.min(axis=0) = {a.min(axis=0)}')
print(f'4. a.min(axis=1) = {a.min(axis=1)}')

print(f'5. a.argmin(axis=1) = {a.argmin(axis=1)}') #we can also retrieve the index of the element

print(f'6. a.max() = {a.max()}') #gets the max. with no axis, array is flatten before processing
print(f'7. a.max() = {a.max(axis=0)}')
print(f'8. a.max() = {a.max(axis=1)}')

print(f'9. a.argmax(axis=0) = {a.argmax(axis=0)}') #we can also retrieve the index of the element

1. a = 
 [[10 30 50]
 [40 20 90]]
2. a.min() = 10
3. a.min(axis=0) = [10 20 50]
4. a.min(axis=1) = [10 20]
5. a.argmin(axis=1) = [0 1]
6. a.max() = 90
7. a.max() = [40 30 90]
8. a.max() = [50 90]
9. a.argmax(axis=0) = [1 0 1]
